' Class Module: ARES_MS_VAR_Class
' Description: This class module represents a configuration variable in MicroStation.
' It encapsulates the properties and behaviors of a configuration variable, including its key, value, and default value.
' License: This project is licensed under the AGPL-3.0.

Option Explicit

' Property to store the key of the configuration variable
Public key As String

' Property to store the value of the configuration variable
Public Value As String

' Property to store the default value of the configuration variable
Public Default As String
