name: Build ARES Installer

on:
  push:
    branches: [ main ]
    paths: 
      - 'installer/**'
      - '.github/workflows/build-installer.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore NuGet packages
      run: nuget restore installer/AresInstaller.sln
      
    - name: Build solution
      run: msbuild installer/AresInstaller.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Create dist directory
      run: |
        New-Item -ItemType Directory -Force -Path dist/latest
        
    - name: Copy installer to dist
      run: |
        Copy-Item installer/AresInstaller/bin/Release/AresInstaller.exe dist/latest/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: AresInstaller
        path: dist/latest/AresInstaller.exe